name: Misc - 题目名称
# CHANGE_ME: 这个标题会显示在全部题目任务列表中，除非太长否则写全名

on:
  push:
    branches: [misc-check-in]
    # CHANGE_ME: 与你所在的分支名保持一致
    paths:
      - "misc-check-in/**"
        # CHANGE_ME: 从根目录开始的路径，你的文件都放在这个路径下
      - ".github/workflows/misc-check-in.yml"
        # CHANGE_ME: 现在这个文件，记得重命名
  workflow_dispatch:

env:
  NAME: misc-check-in
  # CHANGE_ME: 与你的题目文件夹名保持一致

jobs:
  challenge-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.NAME }}
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ env.NAME }}
          tags: |
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.NAME }}/build
          # 这里是 Dockerfile 的路径
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      # 在 docker build 之后要做的事情，这部分你需要的话可以随便改
      # CHANGE_ME: 这题把编译后的文件复制出来，你不需要这一步就注释掉或者删了
      - name: Post build tasks
        working-directory: ${{ env.NAME }}/build
        run: |
          chmod +x post-build.sh
          ./post-build.sh

      # CHANGE_ME: 这题把发给选手的附件作为 artifact 上传，你不需要这一步就注释掉或者删了
      - name: Upload attachments
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}
          path: ${{ env.NAME }}/attachments/

  prune:
    runs-on: ubuntu-latest
    needs: challenge-build
    if: always()
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get lower case package name
        id: lower_pkg
        run: |
          export PKG_NAME="${{ github.event.repository.name }}/${{ env.NAME }}"
          echo "pkg_name=${PKG_NAME@L}" >> $GITHUB_OUTPUT

      - name: Prune old packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ steps.lower_pkg.outputs.pkg_name }}
          exclude-tags: latest
          dry-run: false
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
